### ISSUE TITLE
Cifar_vanilla folder missing

### ISSUE THREAD

**Issue by kingston-aditya** [yangco-le/AdvLatGAN#1]
@yangco-le Hi, I was trying to reproduce the results you presented in your NIPS paper. But I wasn't able to find the Cifar_vanilla directory which you mentioned in the readme.md (evaluation section) for the AdvLatGAN-div. I'd really appreciate it if you could show me the path to the directory.

Thanks!

**Comment by yangco-le** [comment]
Thank you for your interest in our work.

The path `'./cifar_vanilla'` is used for saving the resulting images and trained models during the training process. Initially, this directory does not exist and will only be created once you conduct the training by executing the command `python train.py --dataroot ./data --result_dir './cifar_vanilla' --dataset 'cifar10'`. Also, feel free to assign a different name to the path if you prefer, as it is entirely up to your discretion.

If you have other questions, please feel free to reach out.

**Comment by kingston-aditya** [comment]
Thanks!
